### ISSUE TITLE
Encryption/decryption length depends on input length

### ISSUE THREAD

**Issue by stretch07** [NanderTGA/msgroom-server#1]

**Comment by NanderTGA** [comment]
Then I'll normalize the length. Got an idea on how to do that.

**Comment by NanderTGA** [comment]
Since we are now hashing IPs instead of encrypting, I'll close this issue now.

**Comment by RixInGithub** [comment]
> Since we are now hashing IPs instead of encrypting, I'll close this issue now.

Still quite long hash, since you just `createHash("sha256").update(ip).digest("hex").toUpperCase()`. For me, my browser (chroim by the way) doesn't even send `X-Requested-From`, so I honestly don't know how is my hash even generated. It gives the like as such: `

**Comment by NanderTGA** [comment]
When you send a request, the receiver can always see the ip so it knows where to send the response, otherwise it wouldn't know where to send the response to. Not sure what you're worried about.

**Comment by NanderTGA** [comment]
I'm not sure how secure that would be. We don't want people to get their ips grabbed after all.

**Comment by RixInGithub** [comment]
> now I'm really confused, how are you implementing this? is there a live example anywhere that relies on msgroom-server

A live server of this MsgRoom instance stands on https://nandertga.ddns.org/msgroom (redirects you to port 4096)

**Comment by RixInGithub** [comment]
> hm, his raspi must be off rn but ill wait and check tomorrow

Looks like I mistook the TLD by accident, it's https://nandertga.ddns.net/msgroom/

**Comment by NanderTGA** [comment]
Currently I'm just hashing IPs. MD5 is not recommended for passwords so I thought better safe than sorry and use sha256.
The truth is I am not a security expert. I do not know how secure this hashing + salting would be.

Let's list our requirements:
- consistent IDs
- we need to go from an IP to an ID in the server code and there should not be a way to go back to protect a user's privacy.

Before listing these I thought about aes, which is two-way, and I don't think we want that.
So let's go with hashing + salting.
But what algorithm is sufficiently resistant to brute force attacks? I was told MD5 is not.
