### ISSUE TITLE
Newlines trimming

### ISSUE THREAD

**Issue by RixInGithub** [NanderTGA/msgroom-server#2]
When one of my bots try to send a message with two newlines (`\n\n`), both of them get trimmed. Not a space appears instead, just nothingness. Something like
```
text before newlinestext after newlines
```
I'd really like if this bug were to be patched. I even tried using `\r\n` but it still did the same. Haven't tried using just `\r`, but I guess it'll turn out the same. Is this a problem from MarkdownIt? (I noticed your project uses MarkdownIt) I don't know.

But my bots will look better if you patched this bug. Please?

EDIT: Same bug after using `\r` instead of `\n`.

**Comment by RixInGithub** [comment]
@NanderTGA (urgent(-ish(?)) issue)

**Comment by RixInGithub** [comment]
Added a test for [wawaOS](https://wawaos.glitch.me) for Nander to see the bug in practice.

EDIT: [Source code](https://glitch.com/edit/#!/wawaos?path=server.js%3A65%3A6) proof

**Comment by NanderTGA** [comment]
I think it's some problem related to markdown-it. It normally surrounds each paragraph with `<p>`, which makes messages look too big, and there's no good way to turn it off.

Sorry for not replying earlier, I forgot to finish typing this message.
Anyway I think I have a potential solution.

**Comment by RixInGithub** [comment]
> I think it's some problem related to markdown-it. It normally surrounds each paragraph with `<p>`, which makes messages look too big, and there's no good way to turn it off.
> 
> Sorry for not replying earlier, I forgot to finish typing this message. Anyway I think I have a potential solution.

1. Just as I thought, it's a problem of Markdown-it.
2. <pre>Accepting apology...<br>################ 100%Apology accepted!</pre>
3. I'm excited to see the patch for this bug. #SquattingBugsForEternities!

**Comment by RixInGithub** [comment]
@TheDude53, being the awesome Dude he is (Get it? The Dude?) shared an issue. => https://github.com/markdown-it/markdown-it/issues/211

**Comment by RixInGithub** [comment]
Patched! #SquattingBugsForEternities

**Comment by TheDude53** [comment]
> @TheDude53, being the awesome Dude he is (Get it? The Dude?) shared an issue. => [markdown-it/markdown-it#211](https://github.com/markdown-it/markdown-it/issues/211)

Glad I could help!

**Comment by RixInGithub** [comment]
> > @TheDude53, being the awesome Dude he is (Get it? The Dude?) shared an issue. => [markdown-it/markdown-it#211](https://github.com/markdown-it/markdown-it/issues/211)
> 
> Glad I could help!

:D
