### ISSUE TITLE
feat: give users with the same ID the same colour

### ISSUE THREAD

**Issue by RixInGithub** [NanderTGA/msgroom-server#3]
Could be fixed easily, just as the title says. Originally supposed to be issued by Nander himself.

![Nander wanting me to post this issue](https://github.com/NanderTGA/msgroom-server/assets/87478581/792aa12c-23d9-4d25-a353-890b2a72513c)

**Comment by RixInGithub** [comment]
@NanderTGA You patched this?

**Comment by NanderTGA** [comment]
Yeah, check the commit history.
